"""empty message

Revision ID: 083b836d1a2b
Revises: 7e786d086f22
Create Date: 2019-05-16 14:03:39.670105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083b836d1a2b'
down_revision = '7e786d086f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
