"""empty message

Revision ID: 083d9f18da41
Revises: 88eb3fd8d3d3
Create Date: 2019-05-16 14:01:38.201082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083d9f18da41'
down_revision = '88eb3fd8d3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###
