"""empty message

Revision ID: 3db3887549c6
Revises: 9913a551527f
Create Date: 2019-05-15 13:56:21.247843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db3887549c6'
down_revision = '9913a551527f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('page', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'link', ['page'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='unique')
    op.drop_column('link', 'page')
    # ### end Alembic commands ###
