"""empty message

Revision ID: 45494e7dbb69
Revises: 3db3887549c6
Create Date: 2019-05-15 13:59:59.608011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45494e7dbb69'
down_revision = '3db3887549c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('visits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'visits')
    # ### end Alembic commands ###
