"""empty message

Revision ID: 7e786d086f22
Revises: 083d9f18da41
Create Date: 2019-05-16 14:02:15.855872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e786d086f22'
down_revision = '083d9f18da41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_index(op.f('ix_user_username'), table_name='user')
    # ### end Alembic commands ###
